import 'package:flutter/material.dart';

class HabitIcons {
  const HabitIcons._();

  static const List<IconData> icons = [
    Icons.favorite,
    Icons.favorite_border,
    Icons.fitness_center,
    Icons.directions_run,
    Icons.self_improvement,
    Icons.menu_book,
    Icons.school,
    Icons.work,
    Icons.business_center,
    Icons.laptop,
    Icons.code,
    Icons.water_drop,
    Icons.restaurant,
    Icons.local_cafe,
    Icons.bed,
    Icons.nightlight_round,
    Icons.cleaning_services,
    Icons.check_circle,
    Icons.savings,
    Icons.attach_money,
    Icons.music_note,
    Icons.headphones,
    Icons.palette,
    Icons.camera_alt,
    Icons.flight_takeoff,
    Icons.hiking,
    Icons.pets,
    Icons.emoji_events,
    Icons.sports_soccer,
    Icons.star,
    Icons.psychology,
    Icons.spa,
    Icons.local_fire_department,
    Icons.celebration,
    Icons.volunteer_activism,
    Icons.child_care,
    Icons.groups,
    Icons.home,
    Icons.shopping_cart,
    Icons.local_grocery_store,
  ];
}
